using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace homepage
{
    /// <summary>
    /// Interaction logic for main_page_start.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class main_page_start : ContentPage
    {
        public main_page_start()
        {
            InitializeComponent();
        }
    }
}
	