using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace homepage
{
    /// <summary>
    /// Interaction logic for profile_page.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class profile_page : ContentPage
    {
        public profile_page()
        {
            InitializeComponent();
        }
    }
}
	